### ISSUE TITLE
Is this useable with semantic-ui?

### ISSUE THREAD

**Issue by acidjunk** [BreadMaker/semantic-ui-daterangepicker#1]
The README includes all kind of bootstrap css: so i wonder if this project is a WIP?

**Comment by BreadMaker** [comment]
Yes, this is a quick and dirty port for a personal project. And, yes, this is usable. If you have a specific problem to integrate, please file an issue, and I will gladly help you.

**Comment by BreadMaker** [comment]
Oh, and you can refer to the [examples file](https://github.com/BreadMaker/semantic-ui-daterangepicker/blob/master/examples.html), that I arranged using semantic-ui classes.

**Comment by acidjunk** [comment]
I can confirm it works with the info from the examples.html: maybe a small update in the readme.MD could be handy.

I will create an issue for a small problem I experienced: thanks for this amazing datepicker for Semantic-UI :)
