### ISSUE TITLE
How can I translate?

### ISSUE THREAD

**Issue by meepou** [BreadMaker/semantic-ui-daterangepicker#9]
Hello,

I'd like to know if there is a way to translate the datePicker, thanks

**Comment by andresespinosapc** [comment]
When you initialize it you should set the locale variable. You can see it in the examples.html
E.g. $('.your.class').daterangepicker({
locale: {
                                    applyLabel: 'Submit',
                                    cancelLabel: 'Clear',
                                    fromLabel: 'From',
                                    toLabel: 'To',
                                    customRangeLabel: 'Custom',
                                    daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                                    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                                    firstDay: 1
                                }
});

**Comment by meepou** [comment]
Sorry I forgot I left a message over here ! I have found a solution by downloading my language js from moment.js and then importing it into my page to finally use locale attribute's daterangepicker !
